### ISSUE TITLE
BigInt & BigDecimal does not have .dividedBy() method. 

### ISSUE THREAD

**Issue by itsjerryokolo** [graphprotocol/docs#21]
In the docs, it says BigInt has the `dividedBy()` method. It seems this has been updated to `div()`
Same with BigDecimal. It was renamed to `div()`
I'm on versions: 
`"@graphprotocol/graph-cli": "^0.22.3",` 
`"@graphprotocol/graph-ts": "^0.22.1"`
<img width="558" alt="Screenshot 2022-01-11 at 9 39 29 AM" src="https://user-images.githubusercontent.com/73024324/148909255-29734b14-e25b-49ad-9afb-defb19d65d34.png">

**Comment by azf20** [comment]
Thanks @itsjerryokolo!  @otaviopace are you able to confirm? I am not sure quite [how it is working](https://github.com/graphprotocol/graph-ts/blob/0812c95837c1705fab0bfd05d8c174f6494c0536/common/numbers.ts#L10)

**Comment by otaviopace** [comment]
The docs is incorrect, it should refer to `div` as you mentioned, thanks for the report @itsjerryokolo !

The reason for the `dividedBy` name confusion is probably because besides the `BigInt`/`BigDecimal` types, we also export two namespaces `bigInt` and `bigDecimal`, both which have this function.

Example: https://github.com/graphprotocol/graph-ts/blob/master/common/numbers.ts#L10
