### ISSUE TITLE
Not clear which chain is supported for substreams powered subgraphs   

### ISSUE THREAD

**Issue by pranavdaa** [graphprotocol/docs#535]
It would be great if you guys could make a list of chains that are live for substreams-powered subgraphs Also clearly annotate which products of the graph ecosystem(Hosted service/studio/network) the chain is live on

**Comment by azf20** [comment]
Yes @benface - it isn't currently clear if substreams are supported on the studio, or on the decentralised network (we are looking to add support for more chains on the studio, ahead of support on the network, which is the root cause of this issue).
Not sure if right short-term approach is to adjust this table somehow, or to add a clarifying note underneath

**Comment by azf20** [comment]
Yes @benface that could work well - would we need to update the upstream data model to accommodate?

**Comment by cmwhited** [comment]
> @azf20 – Yes, because `substreams` is currently a single boolean property: https://github.com/edgeandnode/components/blob/main/packages/common/src/models/network-chain.model.ts#L164
> 
> @cmwhited, how do you reckon we should handle this? Would it be OK to change the type of `substreams` to `('studio' | 'network')[]`?

That should be fine, yeah.
